### ISSUE TITLE
MELANIE H. Orientation

### ISSUE THREAD

**Issue by mellodea** [inDevelopme/justaskdavidb#75]
Will complete the following topics under the JustAskDavidB [blog](https://medium.com/indevelopme-tech-coaching-program):

## Articles to Read
- [ ] JustAskDavidB Coaching Program
- [ ] Orientation Packet
- [ ] The Dunn-Kruger Effect
- [ ] Introduction to Queues and Stacks Structure

## Programs to install
Install following programs on computer:

- [ ] [Pycharm Community Version ](https://www.jetbrains.com/pycharm/download)
- [ ] [Docker Desktop](https://www.docker.com/products/docker-desktop/)
- [ ] [Github Desktop](https://desktop.github.com/)

## Accounts to create
Create accounts in the following 3rd Party applications:

- [ ] Github account
- [ ] Linkedin
- [ ] Discord (we will add you to the discord group later)
- [ ] Medium (free account only)

Estimated Time: 5-8 hours

**Comment by justaskdavidb** [comment]
@mellodea  will do this as bug ticket. Where she will create her own orientation packet.
