### ISSUE TITLE
New Member @Melanie H. will create her own Orientation Packet. 

### ISSUE THREAD

**Issue by justaskdavidb** [inDevelopme/justaskdavidb#76]
> Sample ticket that is used can be found here

Will complete the following topics under the JustAskDavidB [blog](https://medium.com/indevelopme-tech-coaching-program):

## Articles to Read
- [ ] JustAskDavidB Coaching Program
- [ ] Orientation Packet
- [ ] The Dunn-Kruger Effect
- [ ] Introduction to Queues and Stacks Structure

## Programs to install
Install following programs on computer:

- [ ] [Pycharm Community Version ](https://www.jetbrains.com/pycharm/download)
- [ ] [Docker Desktop](https://www.docker.com/products/docker-desktop/)
- [ ] [Github Desktop](https://desktop.github.com/)

## Accounts to create
Create accounts in the following 3rd Party applications:

- [ ] Github account
- [ ] Linkedin
- [ ] Discord (we will add you to the discord group later)
- [ ] Medium (free account only)

Estimated Time: 5-8 hours

Resources: 
[Orientation Packet version 1](https://github.com/inDevelopme/justaskdavidb/issues/8)
[Orientation Packet version 2](https://github.com/inDevelopme/justaskdavidb/issues/67)

**Comment by mellodea** [comment]
@mellodea successfully created her [issue ticket](https://github.com/inDevelopme/justaskdavidb/issues/77)

**Comment by mellodea** [comment]
**Painpoints:**  

- wifi / internet


- focus more on the task at hand


**Lessons learned:**  

- navigating gitthub  & older tickets

- markdown syntax

- using chatgpt


**Accomplishment:**
Creating my first issue ticket.

**Comment by mellodea** [comment]
My approach to doing this was:

- Concept
@justaskdavidb  created the issue and we met for 25 minutes to better understand the issue
- Spike + Spike Review
Focused on it 10 miuntes, then met for a 15 minutes spike review
Focused on it for another 15 minutes then met for 15 minutes as a spike review
Focused for another 20 minutes and then met for 15 minutes ...  during that 20 mintues I reviewed  jasmine tickets.

- Implementation

- Peer Review

- CAB Review

- Closure / Completion

**Comment by justaskdavidb** [comment]
@mellodea  completed the assignment in todays session

**Comment by justaskdavidb** [comment]
Complete
